import { z } from "zod";

// Validation Schema using Zod
const schema = z.object({
    name: z.string().min(3, "Please enter your full name"),
    email: z.string().email("Enter a valid email"),
    contact: z.string().min(3, "Enter a valid contact number").max(20).regex(/^\+?[1-9]\d{1,14}$/),
    countryCode: z.string().length(2, "Country code is required"),
    location: z.string().min(3, "Location is required"),
    latlng: z.tuple([z.number(), z.number()]),
    gender: z.enum(["Male", "Female"], { errorMap: () => ({ message: "Select your gender" }) }).optional(),
    birthdate: z.date().optional(),
    maritalStatus: z.enum([
        "Never Married",
        "Divorced",
        "Windowed",
        "Separated",
        "Annulled",
        "Divorced(1 child , Living Together)",
        "Divorced(2 children , Living Together)",
        "Divorced(3 children , Living Together)",
        "Awaiting Divorce",
        "Widowed(1 child , Living Together)",
        "Divorced(Without child)",
    ]).optional(),
    profileNote: z.string().optional(),
    profileMadeBy: z.enum(["Self", "Father", "Mother", "Brother", "Sister", "Cousin", "Friend", "Relative", "Uncle", "Aunty", "Other"]).optional(),
    memberShipType: z.enum(["Active Client", "Free Member", "Inactive", "Deactivated", "Refund", "Old Paid Member", "Profile on Hold"]).optional(),
    registeredBy: z.string().min(3).max(50).optional(),
    amount: z.number().min(0).optional(),
    appearance: z.enum(["Hair-cut", "Turbaned(with trimmed beard)", "Gursikh", "Clean Shaven", "Amrit-Dhari", "Female Profile"]).optional(),
    religion: z.enum(["Sikh", "Hindu", "Jain", "Muslim", "Christain"]).optional(),
    subcaste: z.string().optional(),
    height: z.number().min(0).optional(),
    moreAboutMartialStatus: z.string().optional(),
    vegetarian: z.enum(["Yes", "No"]).optional(),
    doYouDrinkAlcohol: z.enum(["Yes", "No"]).optional(),
    doYouSmoke: z.enum(["Yes", "No"]).optional(),
    phoneNumber: z.number().optional(),
    userCode: z.number().optional(),
    nameOfHighSchool: z.string().optional(),
    education: z.string().optional(),
    employment: z.string().optional(),
    income: z.number().min(0).optional(),
    profession: z.string().optional(),
    familyAffluenceLevel: z.string().optional(),
    fatherEmployment: z.string().optional(),
    motherEmployment: z.string().optional(),
    otherFamilyDetails: z.string().optional(),
    fatherName: z.string().optional(),
    motherName: z.string().optional(),
    residencyStatus: z.string().optional(),
    livingInSince: z.string().optional(),
    countryLiving: z.string().optional(),
    countryGrewUpIn: z.string().optional(),
    propertyDetails: z.string().optional()
});

export default schema;
